# docker-compose.yml
# Simplified orchestration for PostgreSQL, Spark, data generator, and pgAdmin.
# Runs all services in Docker for the e-commerce streaming project.

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./src/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
    networks:
      - ecommerce_network

  spark:
    image: bitnami/spark:3.5.0
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    command: >
      bash -c "
        /opt/bitnami/spark/bin/spark-submit
        --master local[*]
        --packages org.postgresql:postgresql:42.7.3
        /app/src/sparkstream.py
      "
    depends_on:
      - postgres
    networks:
      - ecommerce_network

  data_generator:
    build:
      context: .
      dockerfile: Dockerfile.generator
    volumes:
      - ./data:/app/data
    networks:
      - ecommerce_network

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge